# Generated by Django 5.0.3 on 2024-03-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
