# Generated by Django 5.0.3 on 2024-03-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recipe_author_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
