# Generated by Django 5.0.3 on 2024-03-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_category_recipe_image_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
